version: '3'
services:
  frontend_service:
    container_name: frontend
    build:
      context: frontend
    ports:
      - 5173:5173
      - 3001:3001 # expose vite server hmr port
    develop:
      watch:
        - path: frontend/package.json
          action: rebuild
        - path: frontend/
          target: /app
          action: sync
  backend_service:
    container_name: api
    build:
      context: api
    ports:
      - 8000:8000
    develop:
      watch:
        - path: api/requirements.txt
          action: rebuild
        - path: api/
          target: /app
          action: sync

